### PR TITLE
fixes #10 - skip merging when user doesnt have kube config does not exist

### LINKED ISSUE #10: fails to generate kube config when there is no `~/.kube/config` file in user home directory
**Describe the bug**
When generating kubeconfig, spawner fails if there are not existing kube config at `~/.kube/config`

**To Reproduce**
remove `~/.kube/config` file and run `./spawner kubeconfig`

**Expected behavior**
create new `~/.kube/config` file if does not exist.

**Environment:**
 - OS: Linux

### PR DESCRIPTION
**Pull request by NishanthSpShetty**
# Description

When generating kubeconfig, spawner fails if there are not existing kube config at ~/.kube/config

Fixes #10 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# why

# How Has This Been Tested?

tested running locally, 
- delete ~/.kube/confg
- run the command

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: cmd/client/cli/commands.go [hunk 1]
```diff
@@ -396,20 +401,25 @@ func kubeConfig() *cobra.Command {
...
 			}
 
 			kubeConfg := clientcmdapi.NewConfig()
 			//set the current cluster context as new context
 			newConfig.CurrentContext = res.ClusterName
-			mergo.Merge(kubeConfg, currentKC, mergo.WithOverride)
+			if !skipMerge {
+				mergo.Merge(kubeConfg, currentKC, mergo.WithOverride)
+			}
 			mergo.Merge(kubeConfg, newConfig, mergo.WithOverride)
```
Comment (sid255) [inline cmd/client/cli/commands.go:423]: Should we not remove this?

Comment (NishanthSpShetty) [reply cmd/client/cli/commands.go:423]: looked cleaner in a way taht we are merging existing and new cluster config to new kube config created in line 417

Comment (NishanthSpShetty) [reply cmd/client/cli/commands.go]: cleaned this up.

**Review by sid255 — APPROVED** [review]
LGTM
